name: Run Init Trace

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        # 使用 token 进行检出，确保后续可以推送
        token: ${{ secrets.TRACE_TOKEN }}
        
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: 安装依赖
      run: |
        pip install GitPython
        pip install pathspec
        pip install requests
        
    - name: 运行脚本
      run: python script/init_trace.py
      
    - name: 提交更改
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Auto commit after running init_trace.py"
        git push
